<?php

/** @var Simples\Core\Template\Engine $this */

?>
<nav class="nav has-shadow" id="top">
    <div class="container">
        <div class="nav-left">
            <a href="<?php $this->href('/home'); ?>">
                <img src="<?php $this->image('logo.png') ?>" style="height: 60px; padding: 5px;"  alt="logo"/>
            </a>
        </div>
      <span class="nav-toggle">
        <span></span>
        <span></span>
        <span></span>
      </span>
        <div class="nav-right nav-menu">
            <?php
            if (is_array($this->get('menu', false))) {

                $active = false;
                foreach ($this->get('menu', false) as $href => $text) {
                    $selected = '';
                    if (!$active && $this->match($href)) {
                        $selected = 'is-active';
                        $active = true;
                    }
                    ?>
                        <a class="nav-item is-tab <?php out($selected); ?>" href="<?php $this->href($href); ?>">
                            <?php out($text); ?>
                        </a>
                    <?php
                }
            }
            ?>
            <span class="nav-item">
                <a class="button">
                    Entrar
                </a>
                <a class="button is-info">
                    Cadastrar
                </a>
            </span>
        </div>
    </div>
</nav>
