# v2 syntax
version: '2'

services:

  mysql-simples.cloud:
    image: ambientum/mysql:5.7
    container_name: mysql-simples.cloud
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    ports:
      - "4000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  apache-simples.cloud:
    image: ambientum/php:7.0-apache
    container_name: apache-simples.cloud
    volumes:
      - .:/var/www/app
    ports:
      - "4010:8080"
    links:
      - mysql-simples.cloud