<?php

use Fagoc\Core\App;

?>
<nav class="nav has-shadow">
    <div class="container">

        <div class="nav-left">
            <a class="nav-item is-brand" href="<?php App::route('/'); ?>">
                <img src="http://fagoc.br/download/a/logo" alt="logo"/>
            </a>
        </div>

        <div class="nav-right nav-menu">
            <a class="nav-item" href="<?php App::route('/exercicio/6'); ?>">Exercio 6</a>
            <a class="nav-item" href="<?php App::route('/exercicio/7'); ?>">Exercio 7</a>
            <a class="nav-item" href="<?php App::route('/exercicio/8'); ?>">Exercio 8</a>
        </div>
    </div>
</nav>