<?php

/** @var Simples\Core\Template\Engine $this */

?>
<nav class="nav has-shadow" id="top">
    <div class="container">
        <div class="nav-left">
            <a class="nav-item is-brand" href="<?php $this->href('/home'); ?>">
                <img src="<?php $this->image('logo.png') ?>" alt="logo"/>
            </a>
        </div>
      <span class="nav-toggle">
        <span></span>
        <span></span>
        <span></span>
      </span>
        <div class="nav-right nav-menu">
            <?php
            if (is_array($this->get('menu', false))) {
                foreach ($this->get('menu', false) as $href => $text) {
                    $selected = $this->isActive($href) ? 'is-active' : '';
                    ?>
                        <a class="nav-item is-tab <?php out($selected); ?>" href="<?php $this->href($href); ?>">
                            <?php out($text); ?>
                        </a>
                    <?php
                }
            }
            ?>
            <span class="nav-item">
                <a class="button">
                    Log in
                </a>
                <a class="button is-info">
                    Sign up
                </a>
            </span>
        </div>
    </div>
</nav>
