<?php

return function ($string) {

    /** @var Simples\Core\Template\Engine $this */

    $this->extend('layout/index.phtml', 'index');

    ?>
    <section class="section">

        <div class="container content">
            <div class="heading">
                <h1 class="title">Section</h1>
                <h2 class="subtitle">
                    A simple container to divide your page into <strong><?php out($string); ?></strong>, like the one
                    you're currently reading
                </h2>
            </div>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
                <div class="columns is-vcentered">
                    <div class="column is-5">
                        <figure class="image is-4by3">
                            <img src="<?php $this->image('placeholder/800x600.png') ?>" alt="Description">
                        </figure>
                    </div>
                    <div class="column is-6 is-offset-1">
                        <h1 class="title is-2">
                            Superhero Scaffolding
                        </h1>
                        <h2 class="subtitle is-4">
                            Let this cover page describe a product or service.
                        </h2>
                        <br>
                        <p class="has-text-centered">
                            <a class="button is-large">
                                Learn more
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <?php
};
